name: Tests

on:
  push:
    branches: [main]
  pull_request:
    # Check all PR

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            python-version: "3.11"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: install required packages for tests
      run: |
        pip install .
        pip install -r requirements-test.txt
    - name: run firefox
      run: firefox
    - name: run Python tests
      run: pytest --driver Firefox
